name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Main Site Dependencies
        working-directory: web-ui
        run: npm ci
      
      - name: Install Blog Site Dependencies
        working-directory: web-ui/src/pages/Blog/smileysblog
        run: npm ci

      - name: Deploy the project to GitHub Pages
        working-directory: web-ui
        run: npm run deploy